# frozen_string_literal: true

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 15
